"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type NexusEvent = { id: string; title: string; category: string; priority: "High" | "Medium" | "Low"; type: "task" | "schedule"; date: string; startTime: string; endTime: string; duration: number; status: "pending" | "completed" | "unfinished"; source: "local" | "calendar" | "google-calendar" | "outlook-calendar" | "apple-calendar" | "ai-suggestion"; recurrence?: { unit: "week" | "month"; interval: number; count: number; seriesId: string } };
type View = "day" | "week";
const dateKey = (date: Date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
const addDays = (date: Date, amount: number) => { const next = new Date(date); next.setDate(next.getDate() + amount); return next; };
const minutesToTime = (minutes: number) => `${String(Math.floor(minutes / 60)).padStart(2, "0")}:${String(minutes % 60).padStart(2, "0")}`;
const emptyForm = { title: "", category: "", date: dateKey(new Date()), startTime: "09:00", endTime: "10:00", priority: "Medium" as NexusEvent["priority"], type: "task" as NexusEvent["type"], repeatUnit: "none" as "none" | "week" | "month", repeatInterval: 1, repeatCount: 8 };
const providerDefaults: Record<string, { baseUrl: string; model: string }> = {
  OpenAI: { baseUrl: "https://api.openai.com/v1", model: "gpt-4.1-mini" },
  Qwen: { baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1", model: "qwen-plus" },
  "智谱 AI": { baseUrl: "https://open.bigmodel.cn/api/paas/v4", model: "glm-4.5-flash" },
  DeepSeek: { baseUrl: "https://api.deepseek.com", model: "deepseek-chat" },
  Claude: { baseUrl: "https://api.anthropic.com/v1", model: "claude-sonnet-4-5" },
  Gemini: { baseUrl: "https://generativelanguage.googleapis.com/v1beta", model: "gemini-2.5-flash" },
};

export default function CalendarPage() {
  const [events, setEvents] = useState<NexusEvent[]>([]);
  const [theme, setTheme] = useState<"dark" | "light">("dark");
  const [view, setView] = useState<View>("week");
  const [anchor, setAnchor] = useState(new Date());
  const [ready, setReady] = useState(false);
  const [editorOpen, setEditorOpen] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [form, setForm] = useState(emptyForm);
  const [aiOpen, setAiOpen] = useState(false);
  const [aiProvider, setAiProvider] = useState("OpenAI");
  const [apiKey, setApiKey] = useState("");
  const [aiModel, setAiModel] = useState(providerDefaults.OpenAI.model);
  const [customProvider, setCustomProvider] = useState({ name: "", baseUrl: "", model: "" });
  const [aiSaveMessage, setAiSaveMessage] = useState("");
  const [aiChatOpen, setAiChatOpen] = useState(false);
  const [aiPrompt, setAiPrompt] = useState("");
  const [aiLoading, setAiLoading] = useState(false);
  const [aiError, setAiError] = useState("");
  const [aiProposal, setAiProposal] = useState<{ summary: string; reason: string; event: typeof emptyForm } | null>(null);

  useEffect(() => { try { const raw = localStorage.getItem("nexus-data-v1"); if (raw) { const data = JSON.parse(raw); if (Array.isArray(data.events)) setEvents(data.events.map((item: NexusEvent) => item.date < dateKey(new Date()) && item.status === "pending" ? { ...item, status: "unfinished" } : item)); if (data.theme === "light") setTheme("light"); if (data.aiPlanner?.provider) setAiProvider(data.aiPlanner.provider); if (data.aiPlanner?.apiKey) setApiKey(data.aiPlanner.apiKey); if (data.aiPlanner?.model) setAiModel(data.aiPlanner.model); if (data.aiPlanner?.customProvider) setCustomProvider(data.aiPlanner.customProvider); } } catch {} setReady(true); }, []);
  useEffect(() => { if (!ready) return; try { const data = JSON.parse(localStorage.getItem("nexus-data-v1") || "{}"); localStorage.setItem("nexus-data-v1", JSON.stringify({ ...data, events, theme, aiPlanner: { provider: aiProvider, apiKey, model: aiModel, customProvider } })); } catch {} }, [events, theme, aiProvider, apiKey, aiModel, customProvider, ready]);

  const weekStart = useMemo(() => { const date = new Date(anchor); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - ((date.getDay() + 6) % 7)); return date; }, [anchor]);
  const days = view === "day" ? [anchor] : Array.from({ length: 7 }, (_, index) => addDays(weekStart, index));
  const visibleEvents = events.filter((event) => days.some((day) => dateKey(day) === event.date));
  const hours = Array.from({ length: 15 }, (_, index) => index + 8);

  function buildEvents(input: typeof emptyForm, source: NexusEvent["source"] = "local") {
    const [sh, sm] = input.startTime.split(":").map(Number); const [eh, em] = input.endTime.split(":").map(Number); const duration = Math.max(1, eh * 60 + em - sh * 60 - sm); const seriesId = crypto.randomUUID();
    const count = input.repeatUnit === "none" ? 1 : Math.max(1, Math.min(52, Number(input.repeatCount) || 1));
    return Array.from({ length: count }, (_, index) => { const date = new Date(`${input.date}T12:00:00`); if (input.repeatUnit === "week") date.setDate(date.getDate() + index * Math.max(1, Number(input.repeatInterval)) * 7); if (input.repeatUnit === "month") date.setMonth(date.getMonth() + index * Math.max(1, Number(input.repeatInterval))); return { id: crypto.randomUUID(), title: input.title.trim(), category: input.category.trim() || "其他", date: dateKey(date), startTime: input.startTime, endTime: input.endTime, priority: input.priority, type: input.type, duration, status: "pending" as const, source, ...(input.repeatUnit !== "none" ? { recurrence: { unit: input.repeatUnit, interval: Math.max(1, Number(input.repeatInterval)), count, seriesId } } : {}) }; });
  }
  function saveEvent(event: FormEvent) { event.preventDefault(); if (!form.title.trim()) return; if (editingId) { const replacement = buildEvents({ ...form, repeatUnit: "none" })[0]; setEvents((items) => items.map((item) => item.id === editingId ? { ...item, ...replacement, id: item.id, status: item.status, source: item.source } : item)); } else setEvents((items) => [...items, ...buildEvents(form)]); setEditorOpen(false); setEditingId(null); setForm({ ...emptyForm, date: dateKey(anchor) }); }
  function openEdit(item: NexusEvent) { setEditingId(item.id); setForm({ title: item.title, category: item.category, date: item.date, startTime: item.startTime, endTime: item.endTime, priority: item.priority, type: item.type, repeatUnit: "none", repeatInterval: 1, repeatCount: 1 }); setEditorOpen(true); }
  function moveEvent(id: string, date: string, hour: number) { setEvents((items) => items.map((item) => { if (item.id !== id || item.type === "schedule") return item; const start = hour * 60; return { ...item, date, startTime: minutesToTime(start), endTime: minutesToTime(Math.min(23 * 60 + 59, start + item.duration)) }; })); }
  const shift = (amount: number) => setAnchor((date) => addDays(date, amount * (view === "week" ? 7 : 1)));
  function saveAiSettings() { try { const data = JSON.parse(localStorage.getItem("nexus-data-v1") || "{}"); localStorage.setItem("nexus-data-v1", JSON.stringify({ ...data, aiPlanner: { provider: aiProvider, apiKey, model: aiModel, customProvider } })); setAiSaveMessage("已保存到当前浏览器"); window.setTimeout(() => setAiSaveMessage(""), 2400); } catch { setAiSaveMessage("保存失败，请检查浏览器设置"); } }
  function clearAiKey() { setApiKey(""); setAiChatOpen(false); try { const data = JSON.parse(localStorage.getItem("nexus-data-v1") || "{}"); localStorage.setItem("nexus-data-v1", JSON.stringify({ ...data, aiPlanner: { provider: aiProvider, apiKey: "", model: aiModel, customProvider } })); } catch {} setAiSaveMessage("API Key 已删除"); }
  async function askAi(event: FormEvent) {
    event.preventDefault(); if (!aiPrompt.trim() || !apiKey) return; setAiLoading(true); setAiError(""); setAiProposal(null);
    const nearby = events.filter((item) => item.date >= dateKey(new Date())).slice(0, 30).map((item) => `${item.date} ${item.startTime}-${item.endTime} ${item.title}`).join("\n");
    const instruction = `你是 Nexus Calendar 的规划助手。今天是 ${dateKey(new Date())}。用户需求：${aiPrompt}\n已有安排：\n${nearby || "暂无"}\n请只返回 JSON，不要 markdown：{"summary":"一句建议","reason":"简短原因","event":{"title":"","category":"","date":"YYYY-MM-DD","startTime":"HH:mm","endTime":"HH:mm","priority":"High|Medium|Low","type":"task|schedule","repeatUnit":"none|week|month","repeatInterval":1,"repeatCount":1}}。不要自动修改日程。`;
    try {
      let response: Response; let text = "";
      if (aiProvider === "Gemini") { response = await fetch(`${providerDefaults.Gemini.baseUrl}/models/${encodeURIComponent(aiModel)}:generateContent`, { method: "POST", headers: { "Content-Type": "application/json", "x-goog-api-key": apiKey }, body: JSON.stringify({ contents: [{ parts: [{ text: instruction }] }], generationConfig: { responseMimeType: "application/json" } }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error?.message || "Gemini 请求失败"); text = data.candidates?.[0]?.content?.parts?.[0]?.text || ""; }
      else if (aiProvider === "Claude") { response = await fetch(`${providerDefaults.Claude.baseUrl}/messages`, { method: "POST", headers: { "Content-Type": "application/json", "x-api-key": apiKey, "anthropic-version": "2023-06-01" }, body: JSON.stringify({ model: aiModel, max_tokens: 900, messages: [{ role: "user", content: instruction }] }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error?.message || "Claude 请求失败"); text = data.content?.[0]?.text || ""; }
      else { const baseUrl = aiProvider === "Custom" ? customProvider.baseUrl.replace(/\/$/, "") : providerDefaults[aiProvider]?.baseUrl; if (!baseUrl || !baseUrl.startsWith("https://")) throw new Error("请填写有效的 HTTPS API Base URL"); response = await fetch(`${baseUrl}/chat/completions`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${apiKey}` }, body: JSON.stringify({ model: aiProvider === "Custom" ? customProvider.model || aiModel : aiModel, messages: [{ role: "user", content: instruction }], temperature: .4 }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error?.message || "AI 请求失败"); text = data.choices?.[0]?.message?.content || ""; }
      const parsed = JSON.parse(text.replace(/^```json\s*|\s*```$/g, "").trim()); const proposed = { ...emptyForm, ...parsed.event, repeatInterval: Number(parsed.event?.repeatInterval) || 1, repeatCount: Number(parsed.event?.repeatCount) || 1 }; setAiProposal({ summary: parsed.summary || "AI 已生成一个日程建议", reason: parsed.reason || "根据你的需求和现有安排生成", event: proposed });
    } catch (error) { setAiError(error instanceof Error ? error.message : "暂时无法获取建议。请检查 Provider、模型、Key 和网络设置。"); } finally { setAiLoading(false); }
  }
  function acceptAiProposal() { if (!aiProposal) return; setEvents((items) => [...items, ...buildEvents(aiProposal.event, "ai-suggestion")]); setAiProposal(null); setAiPrompt(""); setAiChatOpen(false); }
  function editAiProposal() { if (!aiProposal) return; setForm(aiProposal.event); setEditingId(null); setEditorOpen(true); setAiChatOpen(false); }

  return <main className={`calendar-shell theme-${theme}`}>
    <div className="ambient ambient-one" /><div className="ambient ambient-two" />
    <header className="calendar-topbar"><a className="brand" href="/"><span className="brand-mark">N</span><span>Nexus</span></a><nav><a href="/">Workspace</a><span>/</span><strong>Calendar</strong></nav><div><button className="theme-toggle" onClick={() => setTheme((value) => value === "dark" ? "light" : "dark")}>{theme === "dark" ? "☀" : "☾"}</button><button className="ai-button" onClick={() => setAiOpen(true)}>✦ AI Planner</button></div></header>
    <section className="calendar-heading"><div><p className="eyebrow"><span /> TIME MANAGEMENT</p><h1>Nexus Calendar</h1><p>安排你的时间，也为真正重要的事情留出空间。</p></div><button className="new-event" onClick={() => { setEditingId(null); setForm({ ...emptyForm, date: dateKey(anchor) }); setEditorOpen(true); }}>＋ New Event</button></section>
    <section className="calendar-toolbar"><div className="date-nav"><button onClick={() => shift(-1)}>←</button><button onClick={() => setAnchor(new Date())}>Today</button><button onClick={() => shift(1)}>→</button><strong>{anchor.toLocaleDateString("zh-CN", { year: "numeric", month: "long", day: view === "day" ? "numeric" : undefined })}</strong></div><div className="view-switch"><button className={view === "day" ? "active" : ""} onClick={() => setView("day")}>Day</button><button className={view === "week" ? "active" : ""} onClick={() => setView("week")}>Week</button></div></section>
    <section className={`calendar-board view-${view}`}>
      <div className="calendar-corner" />{days.map((day) => <div className={`day-head ${dateKey(day) === dateKey(new Date()) ? "today" : ""}`} key={dateKey(day)}><span>{day.toLocaleDateString("en-US", { weekday: "short" })}</span><strong>{day.getDate()}</strong></div>)}
      {hours.map((hour) => [<time className="hour-label" key={`time-${hour}`}>{String(hour).padStart(2, "0")}:00</time>, ...days.map((day) => <div className="calendar-slot" key={`${dateKey(day)}-${hour}`} onDragOver={(event) => event.preventDefault()} onDrop={(event) => moveEvent(event.dataTransfer.getData("text/event-id"), dateKey(day), hour)}>{visibleEvents.filter((item) => item.date === dateKey(day) && Number(item.startTime.slice(0, 2)) === hour).map((item) => <article draggable={item.type === "task"} onDragStart={(event) => event.dataTransfer.setData("text/event-id", item.id)} onClick={() => openEdit(item)} className={`calendar-event ${item.type} ${item.status}`} key={item.id}><span>{item.startTime}</span><strong>{item.title}</strong><small>{item.category} · {item.duration} min</small>{item.type === "schedule" && <b>Fixed schedule</b>}{item.status === "unfinished" && <b>Task unfinished · Change Time</b>}</article>)}</div>)])}
    </section>
    <p className="calendar-hint">拖动 Task 可以调整时间；固定 Schedule 不会被意外移动。所有安排仅保存在当前浏览器。</p>
    {apiKey && <button className="ai-robot" onClick={() => setAiChatOpen(true)} aria-label="打开 AI 规划助手"><span>🤖</span><b>Ask AI</b></button>}

    {editorOpen && <div className="calendar-modal"><button className="modal-backdrop" onClick={() => setEditorOpen(false)} /><form className="event-editor" onSubmit={saveEvent}><header><div><small>EVENT</small><h2>{editingId ? "Edit Event" : "New Event"}</h2></div><button type="button" onClick={() => setEditorOpen(false)}>×</button></header><label>标题<input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} required /></label><div className="editor-grid"><label>日期<input type="date" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} /></label><label>分类<input value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} /></label><label>开始<input type="time" value={form.startTime} onChange={(e) => setForm({ ...form, startTime: e.target.value })} /></label><label>结束<input type="time" value={form.endTime} onChange={(e) => setForm({ ...form, endTime: e.target.value })} /></label><label>优先级<select value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value as NexusEvent["priority"] })}><option>High</option><option>Medium</option><option>Low</option></select></label><label>类型<select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value as NexusEvent["type"] })}><option value="task">Task</option><option value="schedule">Schedule</option></select></label><label className="repeat-field">重复<select value={form.repeatUnit} disabled={!!editingId} onChange={(e) => setForm({ ...form, repeatUnit: e.target.value as typeof form.repeatUnit })}><option value="none">不重复</option><option value="week">每 X 周</option><option value="month">每 X 月</option></select></label>{form.repeatUnit !== "none" && <><label>间隔<input type="number" min="1" max="52" value={form.repeatInterval} onChange={(e) => setForm({ ...form, repeatInterval: Number(e.target.value) })} /></label><label>重复次数<input type="number" min="1" max="52" value={form.repeatCount} onChange={(e) => setForm({ ...form, repeatCount: Number(e.target.value) })} /></label></>}</div>{editingId && <p className="repeat-note">编辑重复日程时只修改当前这一项。</p>}<footer>{editingId && <button type="button" className="delete-event" onClick={() => { setEvents((items) => items.filter((item) => item.id !== editingId)); setEditorOpen(false); }}>Delete</button>}<button type="button" onClick={() => setEditorOpen(false)}>Cancel</button><button className="save-event">Save Event</button></footer></form></div>}
    {aiOpen && <div className="calendar-modal"><button className="modal-backdrop" onClick={() => setAiOpen(false)} /><section className="ai-planner"><header><div><small>OPTIONAL · BYOK</small><h2>✦ AI Planner Settings</h2></div><button onClick={() => setAiOpen(false)}>×</button></header><p>保存 API Key 后，Calendar 右下角会出现机器人。AI 只提供建议，不会自动修改日程。</p><label>Provider<select value={aiProvider} onChange={(e) => { const value = e.target.value; setAiProvider(value); if (providerDefaults[value]) setAiModel(providerDefaults[value].model); }}><option>OpenAI</option><option>Qwen</option><option>Claude</option><option>Gemini</option><option>DeepSeek</option><option>智谱 AI</option><option value="Custom">自定义 Provider</option></select></label>{aiProvider === "Custom" && <div className="custom-provider"><label>Provider 名称<input value={customProvider.name} onChange={(e) => setCustomProvider({ ...customProvider, name: e.target.value })} placeholder="例如：Moonshot" /></label><label>API Base URL<input value={customProvider.baseUrl} onChange={(e) => setCustomProvider({ ...customProvider, baseUrl: e.target.value })} placeholder="https://api.example.com/v1" /></label></div>}<label>模型名称<input value={aiProvider === "Custom" ? customProvider.model : aiModel} onChange={(e) => aiProvider === "Custom" ? setCustomProvider({ ...customProvider, model: e.target.value }) : setAiModel(e.target.value)} placeholder="模型 ID" /></label><label>API Key<input type="password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} placeholder="使用你自己的 API Key" /></label><p className="api-key-note">Provider 配置与密钥只保存在当前浏览器，不会上传到 Nexus 服务器。</p><div className="ai-save-row"><button className="clear-ai-key" onClick={clearAiKey} disabled={!apiKey}>删除密钥</button><span>{aiSaveMessage}</span><button className="save-ai-settings" onClick={saveAiSettings}>保存到本地</button></div></section></div>}
    {aiChatOpen && <div className="calendar-modal"><button className="modal-backdrop" onClick={() => setAiChatOpen(false)} /><section className="ai-chat"><header><div><small>{aiProvider === "Custom" ? customProvider.name || "CUSTOM" : aiProvider} · {aiProvider === "Custom" ? customProvider.model : aiModel}</small><h2>🤖 Plan with AI</h2></div><button onClick={() => setAiChatOpen(false)}>×</button></header><p>告诉 AI 你想完成什么、期限和每周可投入的时间。它会结合近期日程给出一个可编辑建议。</p><form onSubmit={askAi}><textarea value={aiPrompt} onChange={(e) => setAiPrompt(e.target.value)} placeholder="例如：我想在未来 8 周学习 Rust，每周安排两次，每次 90 分钟，尽量放在晚上。" autoFocus /><button disabled={aiLoading || !aiPrompt.trim()}>{aiLoading ? "Planning…" : "Generate Plan"}</button></form>{aiError && <div className="ai-error">{aiError}</div>}{aiProposal && <div className="ai-proposal"><small>AI SUGGESTION</small><h3>{aiProposal.summary}</h3><p>{aiProposal.reason}</p><div><strong>{aiProposal.event.title}</strong><span>{aiProposal.event.date} · {aiProposal.event.startTime}–{aiProposal.event.endTime}</span><span>{aiProposal.event.repeatUnit === "none" ? "单次安排" : `每 ${aiProposal.event.repeatInterval} ${aiProposal.event.repeatUnit === "week" ? "周" : "月"} · 共 ${aiProposal.event.repeatCount} 次`}</span></div><footer><button onClick={() => setAiProposal(null)}>Ignore</button><button onClick={editAiProposal}>Adjust</button><button className="accept-ai" onClick={acceptAiProposal}>Add to Calendar</button></footer></div>}</section></div>}
  </main>;
}
